use_frameworks!

platform :ios, '9.0'

target 'BCAndyAlertView_Example' do
  pod 'BCAndyAlertView', :path => '../'

  target 'BCAndyAlertView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
